# Generated by Django 4.1 on 2022-08-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tutle',
            new_name='title',
        ),
    ]
